---
swagger: "2.0"
info:
  description: "This is API documantation for mobile app developer for ARGO project"
  version: "1.0.0"
  title: "Swagger Argo Mobile"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "kernandrey1@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: ""
basePath: "/v2"
tags:
- name: "Tasks"
  description: "Endpoints for project tasks"
- name: "Customers"
  description: "Endpoints for customers"
- name: "Notes"
  description: "Access to Petstore orders"
schemes:
- "https"
- "http"

paths:
  /api/v1/tasks/:
    get:
      tags:
      - "Tasks"
      summary: "Returns all active tasks  where user is estimator or technician"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/TaskShort"
        401:
          description: "Unauthorized. Token is invalid or expired."
      security:
      - api_key: []

  /api/v1/tasks/<int:task_id>:
    get:
      tags:
      - "Tasks"
      summary: "Returns task details by ID where user is estimator or technician"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: task_id
          in: path
          required: true
          type: integer
          description: "ID of the task to return"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/TaskDetails"
        401:
          description: "Unauthorized. Token is invalid or expired."
        403:
          description: "Forbidden. User is not assigned to this task."
        404:
          description: "Task not found"
      security:
      - api_key: []

  /api/v1/task/<int:task_id>/set-mechanism-status:
    put:
      tags:
        - "Tasks"
      summary: 'Set mechanism status for the task'
      description: ""
      consumes:
          - "application/json"
      produces:
          - "application/json"
      parameters:
          - in: body
            name: body
            description: "Mechanism status object that needs to be added"
            required: true
            schema:
              type: object
              properties:
                mechanism_part_status:
                  type: string
                  required: true
                  description: "Status of the mechanism. Allowed values are: n/a, to_order, ordered, ready_to_pick_up_from_manufacturer, picked_up_from_manufacturer, delivered_to_destination_warehouse"
                  example: "delivered_to_destination_warehouse"
      responses:
          200:
            description: "Successful operation"
            schema:
              type: object
              properties:
                data:
                  type: string
                  example: "Mechanism part status updated successfully."
          400:
            description: 'Bad request. Invalid input.'
          401:
            description: "Unauthorized. Token is invalid or expired."
          403:
            description: "Forbidden. User is not assigned to this task."
          404:
            description: "Task not found"


  /api/v1/customer/<int:customer_id>:
    get:
      tags:
      - "Customers"
      summary: "Returns customer details by ID"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: customer_id
          in: path
          required: true
          type: integer
          description: "ID of the customer to return"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/CustomerDetails"
        401:
          description: "Unauthorized. Token is invalid or expired."
        404:
          description: "Customer not found"
      security:
      - api_key: []


  /api/v1/task/<int:task_id>/notes:
    get:
      tags:
      - "Notes"
      summary: "Returns all notes for the task"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Note"
        401:
          description: "Unauthorized. Token is invalid or expired."
        403:
          description: "Forbidden. User is not assigned to this task."
        404:
          description: "Task not found"
      security:
      - api_key: []

  /api/v1/task/<int:task_id>/note:
    post:
      tags:
        - "Notes"
      summary: "Create a note for the task"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: "Note object that needs to be added"
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                required: true
                description: "Text of the note"
                example: "Hello, this is a note."

      responses:
        201:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Note"
        401:
          description: "Unauthorized. Token is invalid or expired."
      security:
        - api_key: [ ]

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  TaskShort:
    type: object
    properties:
      id:
        type: integer
        example: 62
      name:
        type: string
        example: "Boiler maintenance"
      reference_number:
        type: string
        example: 'T-1'
      client:
        type: string
        example: "Colleen Diaz"
      status:
        type: string
        example: "01_in_progress"
      estimator:
        type: string
        example: "Amy Watson"
      technician:
        type: string
        example: "Amy Watson"

  TaskDetails:
    type: object
    properties:
      id:
        type: integer
        example: 121
      name:
        type: string
        example: "Azure Interior, Brandon Freeman task"
      reference_number:
        type: string
        example: "T-4"
      customer:
        type: object
        properties:
          id:
            type: integer
            example: 27
          name:
            type: string
            example: "Brandon Freeman"
          address:
            type: string
            example: "4557 De Silva St, 94538 Fremont, California, United States"
          phone:
            type: string
            nullable: true
            example: "N/A"
      status:
        type: string
        example: "New"
      assignees:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 2
            name:
              type: string
              example: "Mitchell Admin"
      estimators:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 6
            name:
              type: string
              example: "Abigail Peterson"
      technicians:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 14
            name:
              type: string
              example: "Anita Oliver"
      description:
        type: string
        example: "<p data-oe-version=\"1.0\" data-last-history-steps=\"2960336533123470\">asdasdasd</p>"
      tags:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 3
            name:
              type: string
              example: "Experiment"
      attachments:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1335
            name:
              type: string
              example: "istambul-varna.pdf"
            mimetype:
              type: string
              example: "application/pdf"
            size:
              type: integer
              example: 116755
            store_fname:
              type: string
              example: "da/da02f4646032951ec1af9e289e8e5f7696289d34"
            create_date:
              type: string
              format: date-time
              example: "2025-03-18 08:20:50"
            write_date:
              type: string
              format: date-time
              example: "2025-03-18 08:20:50"
      parts_statuses:
        type: object
        properties:
          glass:
            type: string
            example: "n/a"
          mechanism:
            type: string
            example: "delivered_to_destination_warehouse"
          fwr:
            type: string
            example: "ordered"
          storm:
            type: string
            example: "ready_to_pick_up_from_manufacturer"
          woodwork:
            type: string
            example: "picked_up_from_manufacturer"

  CustomerDetails:
    type: object
    properties:
      id:
        type: integer
        example: 27
      name:
        type: string
        example: "Brandon Freeman"
      title:
        type: string
        example: "Mister"
      address:
        type: string
        example: "4557 De Silva St, 94538 Fremont, California, United States"
      phone:
        type: string
        nullable: true
        example: null
      mobile:
        type: string
        nullable: true
        example: null
      email:
        type: string
        example: "brandon.freeman55@example.com"
      tags:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 7
            name:
              type: string
              example: "Desk Manufacturers"
      previous_tasks:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 77
            name:
              type: string
              example: "Find and fix leak"
            reference_number:
              type: string
              example: "T-1"
            status:
              type: string
              example: "01_in_progress"
            create_date:
              type: string
              format: date-time
              example: "2025-03-07 09:28:22"
      notes:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1167
            message_type:
              type: string
              example: "comment"
            body:
              type: string
              example: "<p>123</p>"
            author_name:
              type: string
              example: "Mitchell Admin"
            create_date:
              type: string
              format: date-time
              example: "2025-03-18 09:36:44"
            write_date:
              type: string
              format: date-time
              example: "2025-03-18 09:36:44"
      attachments:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1336
            name:
              type: string
              example: "istambul-varna.pdf"
            mimetype:
              type: string
              example: "application/pdf"
            size:
              type: integer
              example: 116755
            store_fname:
              type: string
              example: "da/da02f4646032951ec1af9e289e8e5f7696289d34"
            create_date:
              type: string
              format: date-time
              example: "2025-03-18 09:53:17"
            write_date:
              type: string
              format: date-time
              example: "2025-03-18 09:53:17"
      create_date:
        type: string
        format: date-time
        example: "2025-03-07 09:20:55"
      write_date:
        type: string
        format: date-time
        example: "2025-03-18 09:53:09"

  Note:
    type: object
    properties:
      id:
        type: integer
        example: 23
      note:
        type: string
        example: "yet meadow concerned quicker procurement indeed tensely gymnast gah"
      employee:
        type: string
        example: "Amy Watson"

      attachment_ids:
        type: array
        items:
          type: integer
      created_by_app:
        type: boolean
        example: true
      create_date:
        type: string
        format: date-time
        example: "2025-02-10 09:30:26"
